### PR TITLE
Fix use of non existing $data member variable

### LINKED ISSUE #1: MDC::get function bugged
Access to non existing member variable `$data` is performed here:

https://github.com/stevenrombauts/monolog-mdc/blob/75ae205977b3bc79a35b892f0f70b31119e2195e/src/MDC.php#L28

You probably meant to access `$_store` instead

### PR DESCRIPTION
**Pull request by AlexFalappa**
Closes #1

### CODE REVIEW

**Comment by stevenrombauts** [comment]
That could not work at all. Thanks for the PR, @AlexFalappa!

**Comment by AlexFalappa** [comment]
You are welcome @stevenrombauts.

When are you planning to publish a new version on Packagist ?  It would be best for me to depend on a stable version.

**Comment by stevenrombauts** [comment]
@AlexFalappa I tagged a new version v1.1.1 right after I merged it, and it should be available via Packagist right now, if you are OK with pinning the version at v1.1.1 that should work for you?

**Comment by AlexFalappa** [comment]
Perfect @stevenrombauts 

Thank you for your library.

**Pull request merged**
